M48
; DRILL file {KiCad 9.0.2} date 2025-06-26T16:23:08+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-06-26T16:23:08+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0335
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0866
%
G90
G05
T1
X7.2736Y-5.0394
X7.2736Y-5.1575
T2
X7.874Y-3.8484
X9.6555Y-3.8425
M30
